apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app
  labels:
    app: nginx-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: prod-svc
spec:
  type: NodePort
  selector:
    app: nginx-prod
  ports:
    - protocol: TCP
      port: 82
      targetPort: 82